export PS1="\u@\h \w> "
#export PS1=”\e[1;36m\$(date +%a.%H%m%S)\e[m # ”
#export PS1="\n\[\e[32;1m\](\[\e[37;1m\]\u\[\e[32;1m\])-(\[\e[37;1m\]jobs:\j\[\e[32;1m\])-(\[\e[37;1m\]\w\[\e[32;1m\])\n(\[\[\e[37;1m\]! \!\[\e[32;1m\])-> \[\e[0m\]"
ssh-agent bash


keychain ~/.ssh/id_rsa
. ~/.keychain/${HOSTNAME}-sh
